name: Publish Docker image (GHCR)

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'  # pre-releases like v1.0.0-beta
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: vars
        run: |
          TAG=${GITHUB_REF_NAME}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/monoagent:${{ steps.vars.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/monoagent:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/monoagent:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/monoagent:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1


